apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jxq2ivhr8-go
  janus-idp.io/tekton: jxq2ivhr8-go
  backstage.io/kubernetes-id: jxq2ivhr8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jxq2ivhr8-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
